name: my_steam_news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Logo_icon_MySteamNews.png" 

flutter_native_splash:
  color: "#0E385A"
  image: assets/icon/Logo_Splash_MySteamNews.png 
  android: true
  ios: true
  fullscreen: true
